database:
  host: "localhost"
  port: 5432
  name: "my_database"
  user: "my_user"
  password: "my_password"

server:
  host: ""
  port: 0

api:
  api_key: ""
  api_secret: ""
  base_url: ""
  endpoints:
    - uri: "/api/diagnostics/interface/search_arp/"
      method: "POST"
      response_type: "application/json"
      params: ""
      request_body: 
        current: 1
        rowCount: -1
        resolve: "no"

    - uri: "/api/diagnostics/interface/getInterfaceStatistics"
      method: "GET"
      response_type: "application/json"
      params: ""
      request_body: {}

    - uri: "/api/diagnostics/firewall/query_pf_top"
      method: "POST"
      response_type: "application/json"
      params: ""
      request_body:
        current: 1
        rowCount: -1
    
    - uri: "/api/diagnostics/firewall/query_states"
      method: "POST"
      response_type: "application/json"
      params: ""
      request_body:
        current: 1
        rowCount: -1

# Firewall logs stream link. May need to look into doing a websession 
# to continually stream the data and update some table.

    - uri: "/api/diagnostics/firewall/log/"
      method: "GET"
      response_type: "application/json"
      params: ""
      request_body: {}

# Statistics for the firewall interfaces.
    - uri: "/api/diagnostics/firewall/pf_statistics/interfaces"
      method: "GET"
      response_type: "application/json"
      params: ""
      request_body: {}

    - uri: "/api/diagnostics/firewall/log/"
      method: "GET"
      response_type: "application/json"
      params: "digest={digest}&limit={limit}"
      request_body: {}