database:
  host: "localhost"
  port: 5432
  name: "my_database"
  user: "my_user"
  password: "my_password"

server:
  host: ""
  port: 0

api:
  api_key: ""
  api_secret: ""
  base_url: ""
  endpoints:
    - request:
        uri: "/api/diagnostics/interface/search_arp/"
        method: "POST"
        response_type: "application/json"
        params: ""
        request_body: 
          current: 1
          rowCount: -1
          resolve: "no"
      response_obj_type: "ArpTableEntry"

    - request:
        uri: "/api/diagnostics/interface/getInterfaceStatistics"
        method: "GET"
        response_type: "application/json"
        params: ""
        request_body: {}
      response_obj_type: "IFaceStatistics"

    - request:
        uri: "/api/diagnostics/firewall/query_pf_top"
        method: "POST"
        response_type: "application/json"
        params: ""
        request_body:
          current: 1
          rowCount: -1
      response_obj_type: "FirewallSession"
    
    - request:
        uri: "/api/diagnostics/firewall/query_states"
        method: "POST"
        response_type: "application/json"
        params: ""
        request_body:
          current: 1
          rowCount: -1
      response_obj_type: "FirewallState"

# Statistics for the firewall interfaces.
    - request:
        uri: "/api/diagnostics/firewall/pf_statistics/interfaces"
        method: "GET"
        response_type: "application/json"
        params: ""
        request_body: {}
      response_obj_type: "IfaceTraffic"

# Live stream of firewall logs.
    - request:
        uri: "/api/diagnostics/firewall/log/"
        method: "GET"
        response_type: "application/json"
        params: "digest={digest}&limit={limit}"
        request_body: {}
      response_obj_type: "FirewallLogEntry"
